-- Adventskalender 2026 Supabase setup
-- Run this once in the Supabase SQL editor.
--
-- This schema uses username + password for this static GitHub Pages app.
-- It does not use Supabase Auth, so no email addresses or email limits are involved.

create extension if not exists pgcrypto;

grant usage on schema public to anon, authenticated;

drop view if exists public.leaderboard;
drop view if exists public.public_users;
drop function if exists public.register_user(text, text);
drop function if exists public.login_user(text, text);
drop function if exists public.logout_user(uuid);
drop function if exists public.submit_score(uuid, int, int);
drop function if exists public.submit_score(int, int);
drop table if exists public.scores cascade;
drop table if exists public.app_sessions cascade;
drop table if exists public.app_users cascade;
drop table if exists public.profiles cascade;

create table if not exists public.app_users (
  username text primary key,
  password_hash text not null,
  created_at timestamptz not null default now(),
  constraint app_users_username_length check (char_length(trim(username)) between 2 and 20)
);

create table if not exists public.app_sessions (
  token uuid primary key default gen_random_uuid(),
  username text not null references public.app_users(username) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  username text not null references public.app_users(username) on delete cascade,
  day int not null check (day between 1 and 24),
  points int not null check (points between 0 and 10),
  timestamp timestamptz not null default now(),
  constraint scores_one_per_user_day unique (username, day)
);

create index if not exists app_sessions_username_idx on public.app_sessions (username);
create index if not exists scores_day_points_idx on public.scores (day, points desc);
create index if not exists scores_username_day_idx on public.scores (username, day);

alter table public.app_users enable row level security;
alter table public.app_sessions enable row level security;
alter table public.scores enable row level security;

drop view if exists public.leaderboard;
create view public.leaderboard as
  select
    s.username as name,
    s.day,
    s.day as solved,
    s.points,
    s.timestamp
  from public.scores s
  join public.app_users u on u.username = s.username;

drop view if exists public.public_users;
create view public.public_users as
  select username
  from public.app_users;

grant select on public.leaderboard to anon, authenticated;
grant select on public.public_users to anon, authenticated;

create or replace function public.register_user(p_username text, p_password_hash text)
returns table(username text, session_token uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_username text := trim(p_username);
  new_token uuid;
begin
  if char_length(clean_username) < 2 or char_length(clean_username) > 20 then
    raise exception 'Der Username muss 2 bis 20 Zeichen lang sein.';
  end if;

  if char_length(coalesce(p_password_hash, '')) < 32 then
    raise exception 'Das Passwort ist ungueltig.';
  end if;

  insert into public.app_users (username, password_hash)
  values (clean_username, p_password_hash);

  insert into public.app_sessions (username)
  values (clean_username)
  returning token into new_token;

  return query select clean_username, new_token;
exception
  when unique_violation then
    raise exception 'Diesen Username gibt es schon.';
end;
$$;

create or replace function public.login_user(p_username text, p_password_hash text)
returns table(username text, session_token uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  found_username text;
  new_token uuid;
begin
  select app_users.username
  into found_username
  from public.app_users
  where app_users.username = trim(p_username)
    and password_hash = p_password_hash;

  if found_username is null then
    raise exception 'Username oder Passwort stimmt nicht.';
  end if;

  insert into public.app_sessions (username)
  values (found_username)
  returning token into new_token;

  return query select found_username, new_token;
end;
$$;

create or replace function public.logout_user(p_session_token uuid)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.app_sessions
  where token = p_session_token;
$$;

create or replace function public.submit_score(p_session_token uuid, p_day int, p_points int)
returns table(day int, points int, submitted_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  session_username text;
  clean_points int := greatest(0, least(10, p_points));
begin
  select username
  into session_username
  from public.app_sessions
  where token = p_session_token;

  if session_username is null then
    raise exception 'Nicht eingeloggt.';
  end if;

  if p_day < 1 or p_day > 24 then
    raise exception 'Ungueltiger Tag.';
  end if;

  update public.app_sessions
  set last_seen_at = now()
  where token = p_session_token;

  insert into public.scores (username, day, points, timestamp)
  values (session_username, p_day, clean_points, now())
  on conflict (username, day) do update
    set points = greatest(public.scores.points, excluded.points),
        timestamp = case
          when excluded.points > public.scores.points then now()
          else public.scores.timestamp
        end;

  return query
    select s.day, s.points, s.timestamp as submitted_at
    from public.scores s
    where s.username = session_username
      and s.day = p_day;
end;
$$;

revoke execute on function public.register_user(text, text) from public;
revoke execute on function public.login_user(text, text) from public;
revoke execute on function public.logout_user(uuid) from public;
revoke execute on function public.submit_score(uuid, int, int) from public;

grant execute on function public.register_user(text, text) to anon, authenticated;
grant execute on function public.login_user(text, text) to anon, authenticated;
grant execute on function public.logout_user(uuid) to anon, authenticated;
grant execute on function public.submit_score(uuid, int, int) to anon, authenticated;

notify pgrst, 'reload schema';
